/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Menus: typeof import('./src/components/Menus/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
